# Generated by Django 5.2.1 on 2025-05-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuratKeluar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=100)),
                ('penerima', models.CharField(max_length=255)),
                ('tanggal', models.DateField()),
                ('perihal', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='surat_keluar/')),
            ],
        ),
        migrations.CreateModel(
            name='SuratMasuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=100)),
                ('pengirim', models.CharField(max_length=255)),
                ('tanggal', models.DateField()),
                ('perihal', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='surat_masuk/')),
            ],
        ),
    ]
