# Generated by Django 5.2.1 on 2025-06-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=100)),
                ('perihal', models.CharField(max_length=255)),
                ('jenis', models.CharField(choices=[('masuk', 'Surat Masuk'), ('keluar', 'Surat Keluar')], max_length=10)),
                ('tanggal', models.DateField()),
                ('keterangan', models.TextField()),
                ('pengirim', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='surat/')),
            ],
        ),
        migrations.DeleteModel(
            name='SuratKeluar',
        ),
        migrations.DeleteModel(
            name='SuratMasuk',
        ),
    ]
