# Generated by Django 5.2.1 on 2025-06-19 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoKeuangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_keuangan', models.ImageField(blank=True, null=True, upload_to='foto_keuangan/')),
            ],
        ),
        migrations.CreateModel(
            name='Keuangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('tanggal', models.DateField()),
                ('keterangan', models.TextField()),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jenis', models.CharField(choices=[('masuk', 'Pemasukan'), ('keluar', 'Pengeluaran')], max_length=10)),
                ('sisa', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.DeleteModel(
            name='Transaksi',
        ),
        migrations.AddField(
            model_name='fotokeuangan',
            name='keuangan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='keuangan.keuangan'),
        ),
    ]
