# Generated by Django 5.2.1 on 2025-05-23 16:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('no_hp', models.CharField(blank=True, default='0000000000', max_length=15)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('npm', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('prodi', models.CharField(blank=True, choices=[('-', 'Belum Diisi'), ('TI', 'Teknologi Informasi'), ('RPL', 'Rekayasa Perangkat Lunak'), ('RSK', 'Rekayasa Sistem Komputer'), ('ILKOM', 'Ilmu Komunikasi')], default='-', max_length=50)),
                ('semester', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(14)])),
                ('jabatan', models.CharField(blank=True, choices=[('ketua', 'Ketua'), ('sekretaris', 'Sekretaris'), ('bendahara', 'Bendahara'), ('humas', 'Humas'), ('anggota', 'Anggota'), ('Ketua Divisi', 'Ketua Divisi'), ('Ketua Komunitas', 'Ketua Komunitas')], default='Anggota', max_length=20, null=True)),
                ('foto_profil', models.ImageField(blank=True, null=True, upload_to='foto_profil/')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Komunitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('anggota', models.ManyToManyField(related_name='anggota_komunitas', to=settings.AUTH_USER_MODEL)),
                ('kepala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kepala_komunitas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Divisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kepala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kepala_divisi', to=settings.AUTH_USER_MODEL)),
                ('komunitas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisi', to='users.komunitas')),
            ],
        ),
        migrations.CreateModel(
            name='AnggotaDivisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('divisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.divisi')),
            ],
            options={
                'unique_together': {('user', 'divisi')},
            },
        ),
    ]
