# Generated by Django 5.1.2 on 2025-06-20 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_user_no_hp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('divisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='users.divisi')),
                ('kepala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_dipimpin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('status', models.CharField(choices=[('belum_mulai', 'Belum Mulai'), ('sedang_berjalan', 'Sedang Berjalan'), ('selesai', 'Selesai'), ('tertunda', 'Tertunda')], default='belum_mulai', max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projek_manajemen.project')),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('status', models.CharField(choices=[('belum_mulai', 'Belum Mulai'), ('sedang_berjalan', 'Sedang Berjalan'), ('selesai', 'Selesai'), ('tertunda', 'Tertunda')], default='belum_mulai', max_length=50)),
                ('laporan_path', models.FileField(blank=True, null=True, upload_to='laporan_subtask/')),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='projek_manajemen.task')),
            ],
        ),
    ]
