# Generated by Django 5.1.2 on 2025-06-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projek_manajemen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='tanggal_mulai',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='tanggal_selesai',
            field=models.DateField(blank=True, null=True),
        ),
    ]
