# Generated by Django 5.2.1 on 2025-05-23 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('tanggal', models.DateField()),
                ('komunitas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.komunitas')),
            ],
        ),
    ]
