# Generated by Django 5.1.2 on 2025-06-08 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0001_initial'),
        ('users', '0002_alter_user_no_hp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktivitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('status', models.CharField(choices=[('terlaksana', 'Terlaksana'), ('sedang_terlaksana', 'Sedang Terlaksana'), ('tidak_terlaksana', 'Tidak Terlaksana'), ('belum_terlaksana', 'Belum Terlaksana')], default='belum_terlaksana', max_length=20)),
                ('jenis', models.CharField(choices=[('kegiatan', 'Kegiatan'), ('acara', 'Acara')], max_length=20)),
                ('untuk_semua', models.BooleanField(default=False)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('divisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.divisi')),
                ('komunitas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.komunitas')),
            ],
        ),
        migrations.CreateModel(
            name='Gambar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='gambar_kegiatan/')),
                ('aktivitas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gambar_list', to='kegiatan.aktivitas')),
            ],
        ),
        migrations.DeleteModel(
            name='Kegiatan',
        ),
    ]
