# Generated by Django 5.2.1 on 2025-06-19 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kegiatan',
            name='jenis',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kegiatan',
            name='ketua_pelaksana',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kegiatan',
            name='status',
            field=models.CharField(choices=[('terlaksana', 'Terlaksana'), ('tidak_terlaksana', 'Tidak Terlaksana'), ('belum_terlaksana', 'Belum Terlaksana')], default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FotoKegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_kegiatan', models.ImageField(blank=True, null=True, upload_to='foto_kegiatan/')),
                ('kegiatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='kegiatan.kegiatan')),
            ],
        ),
    ]
