# Generated by Django 5.1.2 on 2025-06-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0002_aktivitas_gambar_delete_kegiatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktivitas',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
