# Generated by Django 5.1.2 on 2025-01-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0002_alter_profilpengguna_nama_lengkap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilpengguna',
            name='jabatan',
            field=models.CharField(blank=True, default='Tidak Diisi', max_length=100),
        ),
        migrations.AlterField(
            model_name='profilpengguna',
            name='prodi',
            field=models.CharField(blank=True, choices=[('TI', 'Teknologi Informasi'), ('RPL', 'Rekayasa Perangkat Lunak'), ('RSK', 'Rekayasa Sistem Komputer')], default='TI', max_length=50),
        ),
    ]
