# Generated by Django 5.1.2 on 2025-06-20 08:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0003_alter_aktivitas_deskripsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktivitas',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
