# Generated by Django 5.1.2 on 2025-01-19 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0004_task_subtask_delete_backlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisi',
            name='kepala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kepala_divisi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='komunitas',
            name='kepala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kepala_komunitas', to=settings.AUTH_USER_MODEL),
        ),
    ]
