# Generated by Django 5.1.2 on 2025-01-19 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0005_alter_divisi_kepala_alter_komunitas_kepala'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilpengguna',
            name='divisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kegiatan.divisi'),
        ),
        migrations.AddField(
            model_name='profilpengguna',
            name='komunitas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kegiatan.komunitas'),
        ),
    ]
