# Generated by Django 5.1.2 on 2025-01-26 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0007_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deskripsi',
        ),
        migrations.RemoveField(
            model_name='task',
            name='pengguna',
        ),
        migrations.AddField(
            model_name='task',
            name='id_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='kegiatan.project'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('selesai', 'selesai'), ('sedang_dikerjakan', 'Sedang Dikerjakan'), ('tidak_dikerjakan', 'Tidak Dikerjakan'), ('belum_dikerjakan', 'Belum Dikerjakan')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='tanggal_mulai',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='tanggal_selesai',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SubTask',
        ),
    ]
