# Generated by Django 5.1.2 on 2025-01-26 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0009_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='id_profilepengguna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtask', to=settings.AUTH_USER_MODEL),
        ),
    ]
