# Generated by Django 5.1.2 on 2025-01-28 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0012_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='id_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtask', to='kegiatan.task'),
        ),
    ]
