# Generated by Django 5.1.2 on 2025-01-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0013_alter_subtask_id_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('belum_dikerjakan', 'Belum Dikerjakan'), ('sedang_dikerjakan', 'Sedang Dikerjakan'), ('selesai', 'Selesai')], default='belum_dikerjakan', max_length=20),
        ),
    ]
