# Generated by Django 5.1.4 on 2024-12-23 05:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Divisi',
                'verbose_name_plural': 'Divisi',
            },
        ),
        migrations.CreateModel(
            name='Komunitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Komunitas',
                'verbose_name_plural': 'Komunitas',
            },
        ),
        migrations.CreateModel(
            name='ProfilPengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namadepan', models.CharField(max_length=50)),
                ('namabelakang', models.CharField(max_length=50)),
                ('no_hp', models.CharField(max_length=15)),
                ('prodi', models.CharField(max_length=100)),
                ('semester', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(14)])),
                ('npm', models.CharField(max_length=15, unique=True)),
                ('foto_profil', models.ImageField(blank=True, null=True, upload_to='foto_profil/')),
                ('tanggal_lahir', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil Pengguna',
                'verbose_name_plural': 'Profil Pengguna',
            },
        ),
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('status', models.CharField(choices=[('terlaksana', 'Terlaksana'), ('sedang_terlaksana', 'Sedang Terlaksana'), ('tidak_terlaksana', 'Tidak Terlaksana'), ('belum_terlaksana', 'Belum Terlaksana')], max_length=20)),
                ('jenis', models.CharField(choices=[('kegiatan', 'Kegiatan'), ('acara', 'Acara')], max_length=20)),
                ('divisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kegiatan', to='database.divisi')),
                ('komunitas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kegiatan', to='database.komunitas')),
            ],
            options={
                'verbose_name': 'Kegiatan',
                'verbose_name_plural': 'Kegiatan',
            },
        ),
        migrations.CreateModel(
            name='Gambar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='gambar_kegiatan/')),
                ('kegiatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gambar', to='database.kegiatan')),
            ],
            options={
                'verbose_name': 'Gambar',
                'verbose_name_plural': 'Gambar',
            },
        ),
        migrations.AddField(
            model_name='divisi',
            name='komunitas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisi', to='database.komunitas'),
        ),
        migrations.AddField(
            model_name='komunitas',
            name='anggota',
            field=models.ManyToManyField(blank=True, related_name='anggota_komunitas', to='database.profilpengguna'),
        ),
        migrations.AddField(
            model_name='komunitas',
            name='kepala',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kepala_komunitas', to='database.profilpengguna'),
        ),
        migrations.AddField(
            model_name='divisi',
            name='anggota',
            field=models.ManyToManyField(blank=True, related_name='anggota_divisi', to='database.profilpengguna'),
        ),
        migrations.AddField(
            model_name='divisi',
            name='kepala',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kepala_divisi', to='database.profilpengguna'),
        ),
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlog', to='database.profilpengguna')),
            ],
            options={
                'verbose_name': 'Backlog',
                'verbose_name_plural': 'Backlog',
            },
        ),
    ]
