# Generated by Django 5.1.4 on 2025-01-24 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='pengguna',
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
                ('divisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='database.divisi')),
                ('kepala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kepala_project', to='database.profilpengguna')),
            ],
        ),
        migrations.CreateModel(
            name='Taks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('status', models.CharField(choices=[('belum', 'Belum Dikerjakan'), ('proses', 'Dalam Proses'), ('selesai', 'Selesai')], max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='database.project')),
            ],
        ),
        migrations.CreateModel(
            name='SubTaks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('status', models.CharField(choices=[('belum', 'Belum Dikerjakan'), ('proses', 'Dalam Proses'), ('selesai', 'Selesai')], max_length=20)),
                ('laporan_path', models.FileField(blank=True, null=True, upload_to='laporan_subtasks/')),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='database.profilpengguna')),
                ('taks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='database.taks')),
            ],
        ),
        migrations.DeleteModel(
            name='SubTask',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
