# Generated by Django 5.1.2 on 2024-10-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
                ('nomor', models.IntegerField(max_length=12)),
                ('isi', models.CharField(max_length=512)),
            ],
        ),
    ]
