# Generated by Django 5.2.1 on 2025-06-20 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barang',
            old_name='jumlah',
            new_name='digunakan',
        ),
        migrations.RenameField(
            model_name='barang',
            old_name='lokasi',
            new_name='nama_barang',
        ),
        migrations.RemoveField(
            model_name='barang',
            name='kode',
        ),
        migrations.RemoveField(
            model_name='barang',
            name='nama',
        ),
        migrations.AddField(
            model_name='barang',
            name='ditambah',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barang',
            name='keterangan',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barang',
            name='sebelum',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barang',
            name='sisa',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barang',
            name='tanggal',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FotoBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_barang', models.ImageField(blank=True, null=True, upload_to='foto_barang/')),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='inventaris.barang')),
            ],
        ),
        migrations.DeleteModel(
            name='Peminjaman',
        ),
    ]
